lib/hotdog/application.rb, lib/hotdog/commands/down.rb
hotdog doesn't allow subcommand option.
This request allows all subcommand options and allow scheduled downtime setting for down command.
```
hotdog down --start 2015-03-20 --downtime 86400 hostname hostname ...
```
=> Add configure scheduled downtime

lib/hotdog/application.rb, lib/hotdog/commands.rb, lib/hotdog/commands/search.rb
This option `-x` and `--display-search-tags` to show tags on search result list automatically.
In many cases, I execute hotdog command like below:
```
$ hotdog search -h tag1:foo and tag2:bar-'*' and tag3:baz -a tag1 -a tag2 -a tag3
tag1 tag2 tag3
---- ---- ----
val1 val2 val3
```
This new option make it very simple:
```
$ hotdog search -x -h tag1:foo and tag2:bar-'*' and tag3:baz
host tag1 tag2 tag3
---- ---- ---- ----
host val1 val2 val3
```
Of course, we can specify additional attributes/tags by using `-a`:
```
$ hotdog search -x -h tag1:foo and tag2:bar-'*' and tag3:baz -a mytag
mytag tag1 tag2 tag3
----- ---- ---- ----
tagT  val1 val2 val3
```
=> Add option to show tags which are used in search expressions

README.md, lib/hotdog/commands/search.rb, lib/hotdog/commands/ssh.rb
This pull-request adds "ssh" subcommand so that we can ssh to a server searched using hotdog's search syntax. For example,
```
$ hotdog ssh -i ~/.ssh/td2.pem -u ubuntu -t public_ipv4 myworker-staging
```
This command searches `myworker-staging` servers, and executes `ssh` command to login there. It uses `public_ipv4` tag as the address of the server.
If it found more than 1 servers, it shows search results with index (0, 1, 2, ...) as following, and exits with status code=1:
```
0 123.157.95.30
1 123.211.51.8
2 123.159.41.13
3 123.205.3.1
4 123.45.251.203
I, [2015-04-02T15:34:39.242518 #36208]  INFO -- : found 5 host(s).
```
Instead of showing above search results, you can use `-n INDEX` option to login to Nth server. In this example, following command logins to "0 123.157.95.30":
```
$ …
```
=> Add 'ssh' subcommand

lib/hotdog/commands/ssh.rb
This pull-request adds support for `-A` argument and `-p PORT` arguments to ssh subcommand.
`-A` is for agent forwarding.
=> ssh subcommand supports -A and -p PORT arguments

lib/hotdog/commands/ssh.rb
This pull-request adds support for remote command execution. Command line is passed after '--' argument. For example,
```
$ hotdog ssh -i ~/.ssh/td2.pem -u ubuntu -t public_ipv4 myworker-staging -- uptime
```
=> ssh subcommand accepts command line after '--' that runs on the remote server

hotdog.gemspec, lib/hotdog/commands/pssh.rb
This pull-request adds "pssh" subcommand. This executes the same command on all remote servers. For example, this command runs `uptime` on all searched servers:
```
$ hotdog ssh -i ~/.ssh/td2.pem -u ubuntu -t public_ipv4 myworker-staging -- uptime
53.15.41.13:  05:05:28 up 14 days,  2:50,  0 users,  load average: 6.38, 8.81, 5.82
53.15.51.203:  05:05:28 up 14 days,  2:50,  0 users,  load average: 5.82, 6.77, 4.12
```
You can specify multiple `-t` argument to control the head part of each output lines:
```
$ hotdog ssh -i ~/.ssh/td2.pem -u ubuntu -t public_ipv4 -t host myworker-staging -- uptime
i-ab92c391:  05:05:28 up 14 days,  2:50,  0 users,  load average: 6.38, 8.81, 5.82
i-123dea3f:  05:05:28 up 14 days,  2:50,  0 users,  load average: 5.82, 6.77, 4.12
```
=> Add 'pssh' subcommand

lib/hotdog/commands/hosts.rb
Otherwise, it is possible to get this error:
```
NoMethodError: undefined method `length' for nil:NilClass
```
=> check for truthiness of results

lib/hotdog/commands/search.rb, spec/parser/parser_spec.rb
Fixed parse error with leading keyword (e.g. `unary_op`, `binary_op`) in identifiers and attributes.
=> nothing, android, oreo

lib/hotdog/commands/pssh.rb, lib/hotdog/commands/ssh.rb
This example is dangerous somehow, but is also pretty useful to repeat some contents to remote. Killer feature could be sometime dangerous since it's for killing something 😛 
```sh
% echo echo 'hello, this is $(hostname)' | hotdog pssh environment:development and role:web -- 'eval "$(cat)"'
ip-10-10-151-99.ec2.internal:0:hello, this is ip-10-10-151-99
ip-10-10-155-142.ec2.internal:0:hello, this is ip-10-10-155-142
ip-10-10-157-74.ec2.internal:0:hello, this is ip-10-10-157-74
```
=> Repeat STDIN to each `ssh` children processes invoked by `pssh`

lib/hotdog/commands/ssh.rb
`hotdog ssh` command shows candidates of nodes if search condition matches with multiple hosts. If multiple `-t` option is used, this message becomes broken as following:
```
[frsyuki ~]$ hotdog ssh -h -t public_ipv4 -t environment digdag-server
index host
----- ------------------------------
0     ip-91-18-19-14.ec2.internal
1     production
2     ip-91-18-32-83.ec2.internal
3     development
4     ip-91-18-51-237.ec2.internal
5     development
6     ip-91-18-78-225.ec2.internal
7     staging
8     ip-91-18-2-41.ec2.internal
9     staging
E, [2016-09-06T22:26:27.445952 #56888] ERROR -- : found 10 candidates.
```
Expected result is:
```
[frsyuki ~]$ hotdog ssh -h -t public_ipv4 -t environment digdag-server
index ssh_hostname                   environment
----- …
```
=> Fix candidate message of ssh command with multiple tags

lib/hotdog/expression/syntax.rb
Remove implicit spacing around `atom`.
=> Remove spacing around atom

lib/hotdog/application.rb, lib/hotdog/commands.rb
I added new configuration keys of `api_key_command`, `application_key_command` and `key_command`. With this, we can load credentials in lazy fashion from some external command when it actually needed.
=> Lazy datadog credentials

lib/hotdog/commands.rb, lib/hotdog/commands/down.rb, lib/hotdog/commands/tag.rb, lib/hotdog/commands/untag.rb, lib/hotdog/commands/up.rb
It's retrying after every error. At least for now duplicated calls must be acceptable.
=> Add retry for all dogapi calls

lib/hotdog/commands/scp.rb, lib/hotdog/commands/sftp.rb, lib/hotdog/commands/ssh.rb
We need to _resolve_ the path name just before using it because the value may come from `~/.hotdog/config.yml`.
=> Allow specifying path to SSH configuration as `~/.ssh/config`

lib/hotdog/commands/down.rb, lib/hotdog/commands/tag.rb, lib/hotdog/commands/untag.rb
workaround for `SQLite3::BusyException: database is locked`
=> Add retry to mutation to SQLite database

lib/hotdog/commands.rb, spec/core/commands_spec.rb
With creating `host` tag in SQLite DB, we don't need to special treatment for the virtual tag.
=> Create `host` tag

lib/hotdog/commands.rb, lib/hotdog/expression/semantics.rb, spec/core/commands_spec.rb
This is for keeping result ordering to be deterministic as much as possible.
=> ORDER BY hosts.id

hotdog.gemspec
* oj 2.12.14 doesn't work Ruby 2.4 because of Integer Unification
* too strict version specification prevents noticing compatibility issues.
* hotdog as CLI should use latest libraries to notice breakage faster.
It should specify versions after it really hit the issue.
* applications using hotdog should lock versions by Gemfile.lock.
=> Remove version dependency from gemspec

lib/hotdog/commands/scp.rb
This still doesn't work as expected because `@:` is removed by parse
process.
=> fix scp command help message

lib/hotdog/commands/ssh.rb
As a tentative workaround to avoid mixing up multiple outputs. #51 will be the intrinsic fix for the issue.
=> Application level buffering of outputs

lib/hotdog/formatters/json.rb, spec/formatter/json_spec.rb
**current**
```json
[
[
"ssh_ipv4",
"role"
],
[
"172.18.167.158",
"api3-console"
],
[
"172.18.135.39",
"api3-console"
]
]
```
**after**
```json
[
{
"ssh_ipv4": "172.18.151.74",
"role": "api3-console"
},
{
"ssh_ipv4": "172.18.167.158",
"role": "api3-console"
},
{
"ssh_ipv4": "172.18.135.39",
"role": "api3-console"
}
]
```
The fact that the output structure looks fairly different with headers and without bothers me a bit, but...
Alternative approaches would be:
* use a different format identifier (e.g. ldjson instead of json) and leave the original json format untouched for backwards compatibility
* force headers on when using json format (`options[:headers]` is assumed 'true')
=> make the json output more legible when headers are requested

lib/hotdog/application.rb, lib/hotdog/commands.rb, lib/hotdog/commands/ssh.rb
Sometime `hotdog ssh` returns no result since its `index` filtering worked too early. I moved the filtering after the evaluation of the expression.
=> Fix status handling in ssh

lib/hotdog/application.rb, lib/hotdog/commands.rb, lib/hotdog/commands/down.rb, lib/hotdog/commands/search.rb, lib/hotdog/expression/syntax.rb
Introduced new internal tags of `@host`, `@source` and `@status`. This allows users to use these internal hosts's attribute as a part of expression.
=> `@source` and `@status`

lib/hotdog/commands.rb, lib/hotdog/expression.rb, lib/hotdog/expression/semantics.rb, spec/core/commands_spec.rb, spec/evaluator/glob_expression_spec.rb, spec/evaluator/regexp_expression_spec.rb, spec/evaluator/string_expression_spec.rb, spec/optimizer/glob_expression_spec.rb, spec/optimizer/regexp_expression_spec.rb, spec/optimizer/string_expression_spec.rb, spec/optimizer/unary_expression_spec.rb
Starting from v0.31.0, hotdog started using _internal_ tags with leading `@` in name. This workaround is to keep legacy `host` tag for backward compatibility by rewriting it as the reference to the internal tag of `@host` without any user action.
With 1000+ hosts, it reduced the result SQLite database size in few hundreds KBs.
=> Rewrite the references to `host` by `@host`

lib/hotdog/application.rb, lib/hotdog/commands.rb, lib/hotdog/commands/down.rb, lib/hotdog/commands/search.rb, lib/hotdog/commands/tag.rb, lib/hotdog/commands/untag.rb, lib/hotdog/commands/up.rb, lib/hotdog/sources.rb, lib/hotdog/sources/datadog.rb
Currently the impl is too tightly coupled with DataDog. This PR is to decouple and make DataDog as the default source inventory for future possibility to adopt other sources.
=> support custom data source
