- lib/hotdog/commands/pssh.rb
Show header part in cyan color. Just feel better.
> pssh subcommand shows header part with color

- lib/hotdog/commands/pssh.rb
This option stops execution when a remote execution fails. This is
useful to prevent unexpected accidents when we want to run a command on
many hosts but actually the command was broken.
This code uses exception to interrupt execution because Parallel.map
with in_threads handles exceptions appropriately.
> Add --stop-on-error option to pssh

- lib/hotdog/commands/pssh.rb
> fix return code of pssh

- lib/hotdog/application.rb
- lib/hotdog/commands/search.rb
- lib/hotdog/expression.rb
- lib/hotdog/expression/semantics.rb
- lib/hotdog/expression/syntax.rb
- spec/parser/parser_spec.rb
```sh
% hotdog search 'tail((environment:development and role:app))'
% hotdog search 'head(shuffle((environment:production and role:app)), 3)'
% hotdog search 'group_by((environment:production and role:web and platform:ubuntu), "platform_version")'
```
> Add experimental support for functions

- README.md
- lib/hotdog/commands/search.rb
- lib/hotdog/expression.rb
- lib/hotdog/expression/semantics.rb
- lib/hotdog/expression/syntax.rb
- spec/parser/glob_expression_spec.rb
- spec/parser/parser_spec.rb
- spec/parser/regexp_expression_spec.rb
- spec/parser/string_expression_spec.rb
The wording of _identifier_ is too general. I just replaced them by "tag name".
> Update syntax 20160913

- lib/hotdog/commands/scp.rb
- lib/hotdog/commands/sftp.rb
- lib/hotdog/commands/ssh.rb
Allow users to specify custom SSH configuration file.
> Add `-F` to ssh related commands

- lib/hotdog/commands/search.rb
> Revert "Use Shellwords#shelljoin to handle remote command arguments properly"

- lib/hotdog/expression/semantics.rb
Calling `optimize` was necessary to configure _fallback_ in some expression nodes.
> Call `optimize` on funcall arguments

- lib/hotdog/commands.rb
- lib/hotdog/commands/down.rb
- lib/hotdog/commands/tag.rb
- lib/hotdog/commands/untag.rb
- lib/hotdog/commands/up.rb
With this, we must be able to reduce # of calls of `get_hosts()`.
> Update DB on events

- lib/hotdog/application.rb
- lib/hotdog/formatters/plain.rb
- lib/hotdog/formatters/text.rb
- spec/formatter/plain_spec.rb
- spec/formatter/text_spec.rb
Sometime I'd like to use single space character as separator of output.
> print2 mode

- lib/hotdog/commands.rb
- lib/hotdog/commands/search.rb
- lib/hotdog/commands/tags.rb
- lib/hotdog/expression.rb
- lib/hotdog/expression/semantics.rb
- lib/hotdog/expression/syntax.rb
- spec/parser/glob_expression_spec.rb
- spec/parser/parser_spec.rb
- spec/parser/regexp_expression_spec.rb
- spec/parser/string_expression_spec.rb
> Refactoring; make `tag_name` and `tag_value` as a single word like `tagname`

- lib/hotdog/expression/semantics.rb
- spec/evaluator/glob_expression_spec.rb
- spec/evaluator/regexp_expression_spec.rb
- spec/evaluator/string_expression_spec.rb
- spec/optimizer/glob_expression_spec.rb
- spec/optimizer/regexp_expression_spec.rb
- spec/optimizer/string_expression_spec.rb
Some of nit fixes for future improvements.
> Refactor 20170821

- lib/hotdog/commands/pssh.rb
- lib/hotdog/commands/ssh.rb
> Revert "Add `synchronize` to STDOUT to avoid mixing outputs"

- lib/hotdog/commands/pssh.rb
- lib/hotdog/commands/ssh.rb
> Mutex output 2

- lib/hotdog/expression/semantics.rb
Get rid of mutation from optimizer to make change the behavior easier.
> Refactor 20170828

- lib/hotdog/application.rb
- lib/hotdog/commands.rb
- lib/hotdog/commands/down.rb
- spec/core/commands_spec.rb
Set `mode = 1` if the host is scheduled for some maintenance, instead of hard deleting the records.
> Entry soft deletion

- lib/hotdog/application.rb
- lib/hotdog/commands.rb
- spec/core/commands_spec.rb
> Revert "Add source information"

- lib/hotdog/application.rb
- lib/hotdog/commands.rb
- spec/core/commands_spec.rb
> Revert "Revert "Add source information""

- lib/hotdog/application.rb
- lib/hotdog/commands/ssh.rb
Giving `-v` multiple times on command line will incraese the verbosity
> Add concept of _verbosity_ in logging.

- lib/hotdog/commands/search.rb
- lib/hotdog/commands/ssh.rb
To do limiting before host's status based filtering.
> Do host limitting by rewriting query

- lib/hotdog/commands/up.rb
Now we must not need to remove database on status changes in general. Even if the host is not yet in the local database, the host will be looked up on the next refresh interval.
> Assign `@status:running` after `hotdog up` instaed of removing database

- lib/hotdog/application.rb
- lib/hotdog/commands.rb
Allow subcommand to declare sensible default value for options.
> Fixed a problem implemented in 5003a744a99f3e709046dd1065529f05d3b2a22f

- lib/hotdog/commands.rb
I found some reference to undefined variable.
> The `name` is not defined here
